### ISSUE TITLE
Use CloudFront (or another CDN)

### ISSUE THREAD

**Issue by texdc** [Esri/esri.github.com#44]
S3 is not a CDN.

``` html
<link rel="stylesheet" href="https://s3-us-west-1.amazonaws.com/patterns.esri.com/files/calcite-web/1.0.0-beta.31/css/calcite-web.min.css">
<script src="https://s3-us-west-1.amazonaws.com/patterns.esri.com/files/calcite-web/1.0.0-beta.31/js/calcite-web.min.js"></script>
```

What you're looking for is [CloudFront](https://aws.amazon.com/cloudfront).  You'll want to put your bucket behind a sub-domain, like `cdn.esri.com` or some-such.

``` html
<link rel="stylesheet" href="https://cdn.esri.com/files/calcite-web/1.0.0-beta.31/css/calcite-web.min.css">
<script src="https://cdn.esri.com/files/calcite-web/1.0.0-beta.31/js/calcite-web.min.js"></script>
```

Let me know if you need assistance setting it up.  I'm an [AWS Certified Solutions Architect](https://aws.amazon.com/certification/certified-solutions-architect-associate/).

**Comment by jgravois** [comment]
this website repo doesn't reference any content on S3.

**Comment by texdc** [comment]
```https://s3-us-west-1.amazonaws.com/patterns.esri.com/files/calcite-web/1.0.0-beta.31/css/calcite-web.min.css```

**Comment by jgravois** [comment]
I think you're looking for https://github.com/Esri/calcite-web/issues
