### ISSUE TITLE
Initial page load query

### ISSUE THREAD

**Issue by jf990** [Esri/esri.github.com#51]
should the page load with some query so the project panel is not empty?
@jgravois

**Comment by jgravois** [comment]
for sure. a query that returns the 20 most popular repos would make sense to me.

**Comment by jgravois** [comment]
just realized that a query that returns more than 4 results will bump down the curated categories too much.  perhaps just the four most recently updated projects?

**Comment by jgravois** [comment]
no need to stub a query if we ditch search.
